Add missing includes for FreeBSD
Fixes the following build problems on FreeBSD 10.3:

    script.c:68:2: warning: implicit declaration of function 'sigemptyset' is invalid in C99
    script.c:69:2: warning: implicit declaration of function 'sigaction' is invalid in C99
    script.c:91:14: error: use of undeclared identifier 'AF_INET'

Signed-off-by: Joachim Nilsson <troglobit@gmail.com>